kind: ConfigMap
apiVersion: v1
metadata:
  name: config-demo
  namespace: expense
data:
  DB_HOST: 44.200.190.185

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: expense
  labels:
    app: backend 
    environment: dev 
    project: expense
spec:
  replicas: 2
  selector:
    matchLabels: 
      app: backend 
      environment: dev 
      project: expense
  template:
    metadata:
      labels:
        app: backend 
        environment: dev 
        project: expense
    spec:
      initContainers:
      - name: init-myservice
        image: busybox:1.28
        command: ['sh', '-c', "until nslookup 44.200.190.185; do echo waiting for myservice; sleep 2; done"]
      containers:
      - name: backend
        image: joindevops/backend:v1.0
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "150m"
            memory: "256Mi"
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          failureThreshold: 2
          periodSeconds: 5
          initialDelaySeconds: 30
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
          failureThreshold: 2
          periodSeconds: 5
          initialDelaySeconds: 30
        envFrom:
        - configMapRef:
            name: config-demo

---

apiVersion: v1
kind: Service
metadata:
  name: backend 
spec:
  selector:
    app: backend 
    environment: dev 
    project: expense
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080