kind: ConfigMap
apiVersion: v1
metadata:
  name: config-demo
  namespace: expense
data:
  DB_HOST: mysql 

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: expense
  labels:
    app: backend 
    environment: dev 
    project: expense
spec:
  replicas: 2
  selector:
    matchLabels: 
      app: backend 
      environment: dev 
      project: expense
  template:
    metadata:
      labels:
        app: backend 
        environment: dev 
        project: expense
    spec:
      containers:
      - name: backend
        image: joindevops/backend:v1.0
        env:
          - name: DB_HOST
            valueFrom:
              configMapKeyRef:
                name: config-demo
                key: DB_HOST

---

apiVersion: v1
kind: Service
metadata:
  name: my-service
spec:
  selector:
    app: backend 
    environment: dev 
    project: expense
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080