apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  namespace: expense
  labels:
    app: db 
    environment: dev 
    project: expense
spec:
  replicas: 2
  selector:
    matchLabels: 
      app: db 
      environment: dev 
      project: expense
  template:
    metadata:
      labels:
        app: db 
        environment: dev 
        project: expense
    spec:
      containers:
      - name: mysql
        image: swaroop02/mysql:1.0

---

apiVersion: v1
kind: Service
metadata:
  name: my-service
spec:
  selector:
    app: db 
    environment: dev 
    project: expense
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306